In [1]:
#import numpy as np-------->To import numpy
#numpy.array
#np.array

In [2]:
#Print(dir(statistics))------->this will import directory
#help(statistics.decimal)-------->will give information about decimal

In [3]:
a=[1,2,3]

In [4]:
type(a)

list

In [5]:
import numpy as np

In [6]:
np.array(a)

array([1, 2, 3])

In [7]:
type(a)

list

In [8]:
b=np.array(a)

In [9]:
type(b)

numpy.ndarray

In [10]:
#nd----->nth dimention

In [11]:
b=np.array(a,dtype=complex)

In [12]:
type(b)

numpy.ndarray

In [13]:
b

array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
c=b.T

In [16]:
print(c)

[1.+0.j 2.+0.j 3.+0.j]


In [17]:
type(c)

numpy.ndarray

In [27]:
#Null Array------->np.array(0)

In [28]:
np.array(0)

array(0)

In [22]:
#Create a vector with values ranging from 10 to 49

In [25]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [29]:
#Create a list uptill 1o including 10 then reshape it to 5*2  ,  2*5

In [36]:
z=np.arange(10).reshape(2,5)

In [37]:
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
z=np.arange(10).reshape(5,2)

In [39]:
z

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
#Start:Stop:Jump-------->Slicing Method

In [42]:
L=[1,2,3,4,5,6,7,8,9,10]

In [45]:
L[2::2]

[3, 5, 7, 9]

In [46]:
#Identity Matrix-------->np.eye()  give values inside '()'

In [50]:
x=np.eye(3)

In [51]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
#To create a random array---------->np.random.random(())  give values inside '()'

In [57]:
z=np.random.random((3,3))

In [58]:
z

array([[0.79110211, 0.62699938, 0.49471908],
       [0.09338238, 0.72955109, 0.59434283],
       [0.84237955, 0.27765183, 0.49198809]])

In [59]:
#1 Create a 10*10 array with random values and find the min & max values in the array

In [60]:
#2 Create a random vector of size 30 and find the min value

In [61]:
#3 Create a 2D array with 1 on the border and 0's inside

In [62]:
#4 How to add a border filled with 0's around an existing array

In [63]:
#5 Create a 5*5 matrix with values 1,2,3,4 just below the diagonal

In [64]:
#6 Create a 8*8 matrix and fill it with a checker board pattern

In [65]:
#7 Consider a (6 7 8) shape array, what is the index of x,y,z of the 100th element

In [ ]:
#8 Normalise a 5*5 random matrix