In [ ]:
#1 Implement a function longest word() that takes a list of word and returns the longest word

In [1]:
def main():
    text = input("Please input a list of words to evaluate: ")

    longest = 0

    for words in text.split():
        if len(words) > longest:
            longest = len(words)
            longest_word = words

    print("The longest word is", longest_word, "with length", len(longest_word))

main() 

Please input a list of words to evaluate: Car, Calculator, Mobile
The longest word is Calculator, with length 11


In [24]:
def find_longest_word(words_list):  
    word_len = []  
    for n in words_list:  
        word_len.append((len(n), n))  
    word_len.sort()  
    return word_len[-1][1]  
  
print(find_longest_word(["PHP", "Exercises", "Backend"]))  

Exercises


In [ ]:
#2 Write a Python program to find the area of a triangle using the formula 'Area=(s*(s-a)*(s-b)*(s-c))**0.5'

In [2]:
a = 5
b = 6
c = 7

# Uncomment below to take inputs from the user
# a = float(input('Enter first side: '))
# b = float(input('Enter second side: '))
# c = float(input('Enter third side: '))

# calculate the semi-perimeter
s = (a + b + c) / 2

# calculate the area
area = (s*(s-a)*(s-b)*(s-c)) ** 0.5
print('The area of the triangle is %0.2f' %area)

The area of the triangle is 14.70


In [3]:
#3 Multiply a 5*3 matrix by a 3*2 matrix

In [6]:
import numpy as np
x = np.random.random((5,3))
print("First array:")
print(x)
y = np.random.random((3,2))
print("Second array:")
print(y)
z = np.dot(x, y)
print("Dot product of two arrays:")
print(z)

First array:
[[0.82269927 0.58463501 0.00889288]
 [0.22271372 0.66331999 0.16533283]
 [0.45668215 0.41170406 0.27442108]
 [0.08913256 0.87596858 0.03004983]
 [0.22530478 0.1293114  0.28472968]]
Second array:
[[0.16590023 0.48685004]
 [0.32084047 0.36982327]
 [0.24328001 0.71040799]]
Dot product of two arrays:
[[0.32622403 0.62306038]
 [0.28999032 0.47119312]
 [0.27461616 0.5695444 ]
 [0.3031438  0.3886954 ]
 [0.14813548 0.35978625]]


In [7]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [10]:
#4 Consider two random array a & b, check if they are equal

In [9]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [12]:
#5 Extract the integer parts of a random array using 5 different methods

In [11]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[9. 0. 1. 5. 3. 7. 3. 6. 4. 7.]
[9. 0. 1. 5. 3. 7. 3. 6. 4. 7.]
[9. 0. 1. 5. 3. 7. 3. 6. 4. 7.]
[9 0 1 5 3 7 3 6 4 7]
[9. 0. 1. 5. 3. 7. 3. 6. 4. 7.]


In [14]:
#6 Make an array immutable or read only

In [13]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [15]:
#7 How to print all the values of an array

In [16]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((25,25))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [17]:
#8 How to convert a float array into an integer array

In [18]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)

In [21]:
#9 Consider a random 10*2 matrix represeting Cartesian co-ordinates convert them to Polar co-ordinates

In [22]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.75731521 0.33284019 0.84846701 0.81697835 0.54824584 0.66551518
 1.24099004 1.22136988 0.66543181 0.4324925 ]
[1.29790746 0.78347219 1.2874568  1.30036181 0.17699863 1.3177414
 0.81188898 0.94089265 1.31521572 0.96426411]


In [ ]:
#10 How to find common values between two values

In [23]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


In [ ]:
#11 How to find the dates of today and tomorrow

In [25]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2018-12-22
Today:  2018-12-23
Tomorrow:  2018-12-24
